name: ${name}
version: ${version}
main: ${group}.bolt.BoltPlugin
api-version: 1.13
folia-supported: true
authors: [ ${ author } ]
description: ${description}
commands:
  bolt:
    description: Main bolt command
    permission: bolt.command
  lock:
    description: Shortcut lock command for convenience
    permission: bolt.command.lock
  unlock:
    description: Shortcut unlock command for convenience
    permission: bolt.command.unlock
permissions:
  bolt.mod:
    default: op
  bolt.admin:
    default: op
  bolt.command:
    default: true
  bolt.command.admin:
    default: op
  bolt.command.admin.cleanup:
    default: op
  bolt.command.admin.convert:
    default: op
  bolt.command.admin.debug:
    default: op
  bolt.command.admin.expire:
    default: op
  bolt.command.admin.find:
    default: op
  bolt.command.admin.flush:
    default: op
  bolt.command.admin.purge:
    default: op
  bolt.command.admin.reload:
    default: op
  bolt.command.admin.report:
    default: op
  bolt.command.admin.transfer:
    default: op
  bolt.command.callback:
    default: true
  bolt.command.edit:
    default: true
  bolt.command.group:
    default: true
  bolt.command.help:
    default: true
  bolt.command.info:
    default: true
  bolt.command.info.full:
    default: op
  bolt.command.lock:
    default: true
  bolt.command.mode:
    default: true
  bolt.command.modify:
    default: true
  bolt.command.password:
    default: true
  bolt.command.transfer:
    default: true
  bolt.command.trust:
    default: true
  bolt.command.unlock:
    default: true
  bolt.protection.notify:
    default: op
  bolt.protection.notify.self:
    default: false
  bolt.type.source.door:
    default: false
  bolt.type.access.autoclose:
    default: false
